### ISSUE TITLE
Conditional and referential validations

### ISSUE THREAD

**Issue by kke** [jamesbrooks/hash_validator#12]
How do you validate something like:

```ruby
{
  'married' => 'boolean',
  'spouse_name' => 'string if married otherwise nil'
}
```

Or:

```ruby
{
   'pets' => 'array'
   'favorite_pet' => 'string that is in "pets"'
}
```

**Comment by jamesbrooks** [comment]
Right now not simply, none of the validators (or custom validators) have the ability to look at the state of another part of the hash being validated while validating a particular rule for a key.

`HashValidator::Validator::Base` could be updated to keep a reference to the overall hash as well as current siblings during validation which custom validators could then inspect, which would allow validation similar to what you're looking for.
