### ISSUE TITLE
How can I validate an array of values within a given set?

### ISSUE THREAD

**Issue by djpate** [jamesbrooks/hash_validator#16]
Hello!

I'm playing around with this great gem but I had a question that I can't figure out yet.

let's say I have a hash like

```ruby
events: ['foo', 'bar', 'baz']
```

and I want to validate that the events key is an array and that the values within that array are included in some permitted value how I could achieve that without a proc?

right now my validator looks something like

```ruby
'events' => lambda { |value|
  value.is_a?(Array) && (value - ['foo', 'bar', 'baz']).empty?
}
```

which works fine but I was wondering if the DSL allowed for something that could be translated to JSON and passed to my frontend as well.

**Comment by jamesbrooks** [comment]
Hi,

What you're after can be achieved by building a custom validator specific to your use-case, which is taking a value (being an array), and ensuring every value in that array confirmed to a pre-defined whitelist.

Taking the logic you've got from your proc something like this could do the trick (while still being-re-usable and configurable from some JSON).

```ruby
class HashValidator::Validator::WhitelistValidator < HashValidator::Validator::Base
  def initialize(attribute, whitelist)
    super(attribute)
    @whitelist = whitelist
  end

  def validate(key, value, validations, errors)
    unless value.is_a?(Array) && (value - @whitelist).empty?
      errors[key] = "value must be whitelisted"
    end
  end
end

# Add the validator
events_validator = HashValidator::Validator::WhitelistValidator.new('events', ['foo', 'bar', 'baz'])
HashValidator.append_validator(events_validator)



# Simple case
validator = HashValidator.validate({ events: ['foo'] }, { events: 'events' })
validator.valid?  # => true
validator.errors  # => {}

# Complex success
validator = HashValidator.validate({ events: ['foo', 'bar', 'baz'] }, { events: 'events' })
validator.valid?  # => true
validator.errors  # => {}

# Complex failure
validator = HashValidator.validate({ events: ['foo', 'bar', 'florp'] }, { events: 'events' })
puts validator.valid?  # => false
puts validator.errors  # => {events: "value must be whitelisted"}
```

Here we've designed a whitelist validator that can be used for different kind of fields, in this example we only need one that we'll name `events`.

Does this help at all?

**Comment by djpate** [comment]
It does! Thanks for the help.
