### ISSUE TITLE
[enhancement] Exclusive key validation.

### ISSUE THREAD

**Issue by j3pic** [jamesbrooks/hash_validator#17]
This library would benefit from having an option to prohibit a hash from having any keys not explicitly named in the validation hash. For example:

```
my_hash = { first_name: "John",
            last_name: "Doe",
            invalid: "data that should not be here" }

validation = { first_name: 'string',
               last_name: 'string' }

# Fails because of presence of unexpected key "invalid"
HashValidator.validate(my_hash, validation, exclusive: true)
```

I can put together a PR if we can agree on the interface.

**Comment by jamesbrooks** [comment]
An (undocumented, unfortunately) option does already exist to preform this strict validation, which is invoked by sending true as the third option to `HashValidator.validate`, e.g.

`HashValidator.validate(my_hash, validation, true)`

Though abstracting this out to `strict: true` as well as having it documented would certainly be more desirable :)
