### ISSUE TITLE
ArrayValidator not available when installing from RubyGems

### ISSUE THREAD

**Issue by jorgearimitsu** [jamesbrooks/hash_validator#21]
I noticed that the `ArrayValidator` was added (https://github.com/jamesbrooks/hash_validator/pull/18) but it's not available when installing from RubyGems.

Could you release it? Thanks!

**Comment by jamesbrooks** [comment]
@jorgearimitsu I just released 1.1.0 to RubyGems which now includes ArrayValidator!
