### ISSUE TITLE
Add 'hash' type to stop validation recursion

### ISSUE THREAD

**Issue by gustavoschmidt** [jamesbrooks/hash_validator#7]
First of all, very nice gem!

Use case: `{ access_token: 'string', action: 'string', params: 'hash' }`
I want to make sure I only have these three keys in my hash, but the validation for the params will be done in another part of the code. Is it possible to implement this with the current API? I tried using a '{}' but it fails since it continue the validation on the inner hash.

This would be specially useful with the strict flag true. In a non strict validation, I could omit the params key, but in a strict validation I could not find a way to express this.

If you guys agree this is a good problem to solve, let me know and I'd love to implement the PR.

Cheers

**Comment by gustavoschmidt** [comment]
Sorry folks. Just realized 'required' does exactly that. I'm closing this issue.

**Comment by jamesbrooks** [comment]
No problems @gustavoschmidt, I'm glad you were able to solve your issue :)
