### ISSUE TITLE
Requied field bug when evaluating value is boolean "false"

### ISSUE THREAD

**Issue by KateWilkins** [jamesbrooks/hash_validator#8]
>>  valid = { "value" => "required" }

>>  test1 = { "value" => false }
>>  test2 = { "value" => true }
>>  test3 = { "value" => "Fruitbat" }

>>  HashValidator.validate(test3,valid).valid?
=> true
>>  HashValidator.validate(test2,valid).valid?
=> true
>>  HashValidator.validate(test1,valid).valid?
=> false

All of the 3 evaluations should validate true.

**Comment by jamesbrooks** [comment]
This has been fixed in 0d21d41790ce86b74f90cb08bbca24ac0b391046. A new gem version (0.5.0) has been released with this fix included.

Thanks for reporting this!
